services:
  postgres:
    image: postgres:17
    container_name: postgres_auth
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "listen_addresses=*"]
    env_file:
      - .env

volumes:
  pg_data:
